In [1]:
import numpy as np
import random

In [2]:
calles = []
with open("Calles.txt") as f:
  for line in f:
    calle = line.split()
    calles.append(*calle)
print(calles)

['Av.1', 'C.2', 'C.3', 'C.4', 'C.5', 'C.6', 'Av.7', 'C.8', 'C.9', 'C.10', 'C.11', 'C.12', 'Calle_14', 'C.15', 'C.16', 'C.17', 'C.18', 'Av.19', 'C.20', 'C.21', 'C.22', 'C.23', 'C.24', 'Av.25', 'C.26', 'C.27', 'Calle_28', 'C.29', 'C.30', 'Av.31', 'C.132', 'C.133', 'C.134', 'C.135', 'C.136', 'Av.137', 'C.138', 'C.139', 'C.140', 'C.141', 'C.142', 'C.143', 'C.521', 'C.522', 'C.523', 'C.524', 'C.525', 'C.526', 'C.527', 'C.528', 'C.529', 'C.530', 'C.531', 'Av.32', 'C.33', 'C.34', 'C.35', 'C.36', 'C.37', 'Av.38', 'Calle_39', 'C.40', 'C.41', 'Calle_42', 'C.43', 'Av.44', 'C.45', 'C.46', 'C.47', 'C.48', 'C.49', 'C.50', 'Av.51', 'Av.53', 'C.54', 'C.55', 'C.56', 'C.57', 'C.58', 'C.59', 'Av.60', 'C.61', 'C.62', 'C.63', 'C.64', 'C.65']


In [3]:
def generarIntersecciones(calles, archivo, nfilas, ncol, datos):
  n = len(calles)
  if n == nfilas + ncol:
    #Asignar numeros a las calles
    num = 0
    dicc_c = {}
    for calle in calles:
      dicc_c[calle] = num
      num += 1
    
    #Inicializamos el mapa que simule las intersecciones con puros -1  
    I = np.zeros([nfilas,ncol], int)
    I = I - 1

    #Actualizamos la matriz, poniendo los nodos de intersecciones
    with open(archivo) as f:
      for line in f:
        nodo, fila, columna, y, x = [elem for elem in line.split()]
        I[dicc_c[fila], dicc_c[columna] - nfilas] = int(nodo)
        datos[int(nodo)] = (float(x), float(y))

  return I

In [4]:
class Perlin:
    def __init__(self):
        self.gradients = []
        self.lowerBound = 0


    def valueAt(self, t,max):
        if(t<self.lowerBound):
            print("ERROR: Input parameter out of bounds!")
            return
        while t >= len(self.gradients)-1+self.lowerBound:
            self.gradients.append(random.uniform(1, max))

        discarded = int(self.lowerBound) # getting number of gradients that have been discarded
        # Compute products between surrounding gradients and distances from them
        d1 = (t-t//1)
        d2 = d1-1
        a1 = self.gradients[(int)(t//1)-discarded]*d1
        a2 = self.gradients[(int)(t//1+1)-discarded]*d2

        amt = self.__ease(d1)

        return self.__lerp(a1,a2,amt)

    def discard(self, amount):
        gradientsToDiscard = int(amount+self.lowerBound%1)
        self.gradients = self.gradients[gradientsToDiscard:]
        self.lowerBound += amount

    def __ease(self, x):
        return 6*x**5-15*x**4+10*x**3


    def __lerp(self, start, stop, amt):
        return amt*(stop-start)+start

In [5]:
import random
import statistics
import matplotlib.pyplot as plt

def updateTraffic(hour):
  noise=Perlin()
  time=[i*0.01 for i in range(1729)]
  if hour>22 or hour<4:
    values=[int(abs(noise.valueAt(i,20)*2)) for i in time]
    return values
  if hour>=4 and hour<10:
    values=[int(abs(noise.valueAt(i,50)*10)) for i in time]
    return values
  if hour>=10 and hour<14:
    values=[int(abs(noise.valueAt(i,35)*8)) for i in time]
    return values
  if hour>=14 and hour<22:
    values=[int(abs(noise.valueAt(i,45)*10)) for i in time]
    return values
 

In [6]:
ahh=updateTraffic(15)
print(max(ahh))
print(ahh)

112
[0, 3, 6, 9, 12, 14, 17, 20, 23, 26, 28, 31, 33, 35, 37, 39, 41, 43, 45, 46, 48, 49, 50, 51, 52, 53, 53, 53, 54, 54, 54, 53, 53, 53, 52, 51, 50, 49, 48, 47, 46, 44, 43, 41, 39, 37, 36, 34, 31, 29, 27, 25, 23, 21, 18, 16, 14, 11, 9, 7, 5, 3, 0, 1, 3, 5, 6, 8, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 21, 21, 22, 22, 22, 22, 21, 21, 20, 19, 18, 17, 16, 15, 14, 12, 10, 9, 7, 5, 3, 1, 0, 1, 3, 5, 7, 9, 10, 12, 14, 15, 16, 18, 19, 20, 20, 21, 22, 22, 22, 23, 23, 22, 22, 22, 21, 21, 20, 19, 18, 17, 15, 14, 13, 11, 9, 8, 6, 4, 2, 0, 1, 3, 5, 7, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 37, 39, 40, 42, 43, 44, 45, 46, 47, 48, 48, 48, 49, 49, 49, 49, 49, 48, 48, 47, 46, 45, 44, 43, 41, 40, 38, 37, 35, 33, 31, 28, 26, 24, 21, 19, 16, 13, 11, 8, 5, 2, 0, 2, 5, 8, 11, 13, 16, 18, 21, 23, 25, 27, 29, 31, 33, 34, 35, 37, 38, 38, 39, 39, 40, 40, 40, 40, 39, 39, 38, 37, 36, 35, 34, 33, 31, 29, 28, 26, 24, 22, 20, 17, 15, 13, 10, 8, 5, 3, 0, 1, 4, 6, 9, 11, 14, 16, 19, 21, 23, 26, 28, 3

In [8]:
datos = {}
I = generarIntersecciones(calles, "Intersecciones con coordenadas.txt", 42, 44, datos)
print(I)
print(datos)

[[   0    1   -1 ...   35   36   37]
 [  38   39   -1 ...   74   75   76]
 [  77   78   79 ...  118  119  120]
 ...
 [1607 1608 1609 ... 1648 1649 1650]
 [1651 1652 1653 ... 1687 1688 1689]
 [1690 1691 1692 ... 1726 1727 1728]]
{0: (-57.976523, -34.885116), 1: (-57.974166, -34.887932), 2: (-57.967053, -34.89187), 3: (-57.966013, -34.892609), 4: (-57.964961, -34.893386), 5: (-57.963899, -34.894156), 6: (-57.962831, -34.894975), 7: (-57.961672, -34.895855), 8: (-57.960551, -34.8967), 9: (-57.959387, -34.897535), 10: (-57.958293, -34.898376), 11: (-57.957182, -34.899199), 12: (-57.954865, -34.900923), 13: (-57.953728, -34.901799), 14: (-57.95256, -34.902535), 15: (-57.951425, -34.90341), 16: (-57.950321, -34.904207), 17: (-57.949226, -34.905021), 18: (-57.947912, -34.905919), 19: (-57.946834, -34.906706), 20: (-57.945938, -34.907454), 21: (-57.945123, -34.908123), 22: (-57.944345, -34.908721), 23: (-57.943578, -34.909192), 24: (-57.942918, -34.909698), 25: (-57.941663, -34.910582), 26: (-

In [9]:
import math
def haversine(lat1, lon1, lat2, lon2):
    rad=math.pi/180
    dlat=lat2-lat1
    dlon=lon2-lon1
    R=6372.795477598
    a=(math.sin(rad*dlat/2))**2 + math.cos(rad*lat1)*math.cos(rad*lat2)*(math.sin(rad*dlon/2))**2
    distancia=2*R*math.asin(math.sqrt(a))
    return distancia

In [10]:
def peso2calculo(trafficValue):
  a=50-trafficValue
  if a>=25:
    peso2=1.3
    return peso2
  else:
    peso2=0.7
    return peso2

In [11]:
def generarListaAdyacencia2(I, datos,hora):
  G = []
  nfilas, ncol = np.shape(I) 
  values=updateTraffic(hora)
  #Agregar las adyacencias de cada nodo
  for i in range(nfilas):
    for j in range(ncol):
      if I[i,j] > -1:
        aux = []
        x1, y1 = datos[I[i,j]]
        #arriba
        if (i > 0) and (I[i-1, j] > -1):
          x2, y2 = datos[I[i-1, j]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i-1, j], peso))
        #izquierda
        if (j > 0) and (I[i, j-1] > -1):
          x2, y2 = datos[I[i, j-1]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i, j-1], peso))
        #derecha (bug)
        if (j < ncol-1) and (I[i, j+1] > -1):
          x2, y2 = datos[I[i, j+1]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i, j+1], peso))
        #abajo (bug)
        if (i < nfilas-1) and (I[i+1, j] > -1):
          x2, y2 = datos[I[i+1, j]]
          peso1 = haversine(x1,y1,x2,y2)
          traficcValue=values[i+1]
          peso2=peso2calculo(traficcValue)
          peso=peso1*peso2
          aux.append((I[i+1, j], peso))
        G.append(aux)

  #Guardar en un archivo
  cont = 0
  with open("Lista_Adyacencia_Generado2.txt", 'w') as archivo:
    for lista in G:
      for num in lista:
        archivo.write(str(num) + " ")
      archivo.write("\n")

  return G

In [12]:
a = generarListaAdyacencia2(I, datos,9)
print(a)

[[(1, 0.40344964974194214), (38, 0.11916216347451197)], [(0, 0.40344964974194214), (39, 0.1430240997956625)], [(3, 0.16070423868135952), (40, 0.11265717573480842)], [(2, 0.16070423868135952), (4, 0.1633700598900751), (41, 0.11124244482521904)], [(3, 0.1633700598900751), (5, 0.16452435993900139), (42, 0.11762438821230566)], [(4, 0.16452435993900139), (6, 0.16671453624381127), (43, 0.12092064177938132)], [(5, 0.16671453624381127), (7, 0.1806676130252551), (44, 0.14391652476602135)], [(6, 0.1806676130252551), (8, 0.17456922467559954), (45, 0.15692373841420526)], [(7, 0.17456922467559954), (9, 0.180083562798282), (46, 0.16065818923951472)], [(8, 0.180083562798282), (10, 0.17083585573838608), (47, 0.16542740932503608)], [(9, 0.17083585573838608), (11, 0.17260531526433023), (48, 0.1554421375390512)], [(10, 0.17260531526433023), (49, 0.1577335310338247)], [(13, 0.1776102088091278), (51, 0.15466055846479176)], [(12, 0.1776102088091278), (14, 0.17807626481837574), (52, 0.1587985074032013)], [(1

In [13]:
import heapq as hq
import math

In [14]:
def dijkstra(G, s, e, p):
  n = len(G)
  visited = [False]*n
  path = [-1]*n
  cost = [math.inf]*n

  cost[s] = 0
  pqueue = [(0, s)]
  while pqueue:
    g, u = hq.heappop(pqueue)
    if u == e:
      break
    if not visited[u]:
      visited[u] = True
      for v, w in G[u]:
        if not visited[v]:
          f = g + w
          if f < cost[v]:
            if (v == e) and (f <= p):
              pass
            else:
              cost[v] = f
              path[v] = u
              hq.heappush(pqueue, (f, v))
            
  return path, cost

In [15]:
def spath(path, e, sp):
  if path[e] != -1:
    spath(path, path[e], sp)
  sp.append(e)
  return sp

In [20]:
p = 0
sp = []
first = 0
end = 38
path, cost = dijkstra(a, first, end, p)
print(spath(path, end, sp))
print(cost[end])
p = cost[end]

[0, 38]
0.11916216347451197


In [21]:
sp = []
first = 0
end = 38
path, cost = dijkstra(a, first, end, p)
print(spath(path, end, sp))
print(cost[end])
p = cost[end]

[0, 1, 39, 38]
0.7143862663091605


In [22]:
sp = []
first = 0
end = 38
path, cost = dijkstra(a, first, end, p)
print(spath(path, end, sp))
print(cost[end])
p = cost[end]

[0, 1, 39, 78, 77, 38]
1.042736640206572
